# Generated by Django 4.2.4 on 2023-09-09 02:31

from django.db import migrations, models
import strawberry_django_auth.refresh_token.models


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry_django_auth', '0002_rename_revoked_refreshtoken_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(default=strawberry_django_auth.refresh_token.models.RefreshToken.generate, editable=False, max_length=255, unique=True),
        ),
    ]
